
services:
  mysql-db-customer:
    image: mariadb:10.6
    container_name: mysql-db-customer
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: customer-db
      MYSQL_USER: youness
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 15s
      retries: 10


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "9999:80"
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-db-customer
      PMA_PORT: 3306



  postgres-service:
    image: postgres
    container_name: postgres-service
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: k1234
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"


  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: youness@slimi.net
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin-data:/var/lib/pgadmin


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-service:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: k1234
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      postgres-service:
         condition: service_healthy
  angular-front-end:
    build: ./angular-app
    container_name: angular-front-end
    ports:
      - '4200:80'
    expose:
      - '4200'
    restart: always

#  customer-service:
#    build: ./customer-service
#    container_name: customer-service
#    ports:
#      - '8090:8090'
#    expose:
#      - '8090'
#    depends_on:
#      - keycloak
#    environment:
#      - DB_URL=jdbc:mysql://mysql-db-customer:3306/customer-db?createDatabaseIfNotExist=true
#      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/ebank-realm
#      - KEYCLOAK_JWK_URI=http://keycloak:8080/realms/ebank-realm/protocol/openid-connect/certs

volumes:
  mysql-data:
  postgres-data:
  pgadmin-data:
